spring.application.name=demo
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:7432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.enabled=true
spring.jpa.show-sql=true