spring.application.name=demo
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:7432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.enabled=true
spring.jpa.show-sql=true
logging.level.org.hibernate.stat=DEBUG